server {
    listen 80;
    server_name camilassilvapsi.com.br www.camilassilvapsi.com.br;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    gzip on;
    gzip_types text/css application/javascript image/svg+xml;
}

server {
    listen 443 ssl;
    server_name camilassilvapsi.com.br www.camilassilvapsi.com.br;

    ssl_certificate     /etc/nginx/certs/cert.pem;
    ssl_certificate_key /etc/nginx/certs/key.pem;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    gzip on;
    gzip_types text/css application/javascript image/svg+xml;
}
